---
name: Chase Clark
address: "University of Wisconsin-Madison, School of Pharmacy, VCRGE/BIOTECH/GENOMICS"
www: chasemc.github.io
email: "chasingmicrobes@gmail.com"
twitter: ChasingMicrobes
github: chasemc
linkedin: hirechase
date: "`r format(Sys.time(), '%B %Y')`"
output: function(...) {source('resume_entries.R');vitae:::set_entry_formats(resume_entries);vitae::cv_document(..., template = "resume_template.tex", citation_package = "biblatex")}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(vitae)
library(data.table)
library(glue)
library(lubridate)
library(dplyr)
library(jsonlite)
library(rorcid)
orcid_auth()
pipe_assign <- function(x) x
```


```{r orcid-data}
rorcid::orcid_educations("0000-0001-6439-9397")$`0000-0001-6439-9397`$`affiliation-group`$summaries |>
  data.table::rbindlist(fill = T) |>
  pipe_assign() -> orcid_data
```

# Employment

```{r employment}
temp <- cbind.data.frame(orcid_data[, c('education-summary.role-title','education-summary.end-date.year.value',
                                        'education-summary.organization.name')], 
                         paste0(orcid_data$'education-summary.organization.address.city',
                                ", ",
                                orcid_data$'education-summary.organization.address.region' ))

colnames(temp) <- c('Degree',
                    'Year',
                    'Institution',
                    'Where')

detailed_entries(data = temp,
                 what = Degree, 
                 when = Year,
                 with =  Institution,
                 where = Where)
```

# Experience

```{r experience}
job_titles <- data.table::fread(here::here("data", "job-titles.csv"), sep = "\t")

job_descriptions <- data.table::fread(here::here("data", "job-descriptions.csv"), sep = ",")

jobs <- merge(job_titles, 
                          job_descriptions, 
                          by = "jobId", 
                          all.x = T) 

data.table::setorderv(jobs,
                      c("begin","descId"),
                      order=c(-1, 1))


vitae::detailed_entries(jobs,
                        what = position,
                        when = as.character(
                          glue("{lubridate::month(begin, label = TRUE, abbr = TRUE)} {lubridate::year(begin)} - 
           {ifelse(!is.na(end), 
           paste(lubridate::month(end, label = TRUE, abbr = TRUE), lubridate::year(end)), 'present')}")),
           with = employer,
           where = glue("{city}, {region}, {country}"),
           why = accomplishments)
```

\newpage

# Skills

```{r, skills, results='asis', width = 40000}

skills <- data.table::fread(here::here("data", "skills.csv"))

skills_formatted <- skills %>% 
  mutate(skill = if_else(is.na(details), glue("{skill}"), glue("{skill} ({details})"))) %>% 
  group_by(group) %>% 
  summarize(skills = glue_collapse(skill, sep = " $\\bullet$ "))

skills_formatted$skills <- gsub("()", "",skills_formatted$skills,fixed = TRUE)

for (group in skills_formatted$group) {
  cat(
    glue("\\textbf{<<tools::toTitleCase(group)>>}:", .open = "<<", .close = ">>"),
    filter(skills_formatted, group == !!group)$skills,
    "\n\n\n"
  )
}
```

# Select Individual Software Projects

```{r software-individual}

software <- data.table::fread(here::here("data/software.csv"), sep = "\t")

software <- software[software$group == "solo", ]

detailed_entries(data = software[order(software$year, decreasing = T),],
                 what = name,
                 when = year,
                 with = language,
                 where = description)
```

# Select Team Software Projects

```{r software-team}

software <- data.table::fread(here::here("data/software.csv"), sep = "\t")

software <- software[software$group == "team", ]

detailed_entries(data = software[order(software$year, decreasing = T),], 
                 what = name,
                 when = year,
                 with = language,
                 where = description)

```

# Talks

```{r talks}

oral <- data.table::fread(here::here("data/oral_contributed.csv"), sep = "\t")

detailed_entries(data = oral[order(as.Date(oral$year), decreasing = T),],
                 what = meeting, 
                 when = year,
                 why = title)
```

# Awards

```{r awards}

grants <- data.table::fread(here::here("data/awards.csv"), sep = "\t")

brief_entries(data =  grants[order(vapply(strsplit(grants$year, "-"), function(x) as.integer(x[[1]]), 1), decreasing = T),],
              what = award,
              when = year,
              with = amount)

```

# Workshops

```{r workshops}
workshops <- data.table::fread(here::here("data/workshops.csv"), sep = "\t")

setorderv(workshops,
          c("begin"),
          order=-1)

detailed_entries(workshops,
                 what = name,
                 when = as.character(
                   glue("{lubridate::month(begin, label = TRUE, abbr = TRUE)} {lubridate::year(begin)} "))
)
```

# Publications

```{r publications, include=FALSE}

puburls <- data.table::fread(here::here("data","papers.csv"))$doi
crossref_api <- paste0("https://api.crossref.org/v1/works/", puburls)

pubs <- lapply(crossref_api, 
               function(x){
                 jsonlite::fromJSON(x)$message
               })

pub_dates <- sapply(pubs, 
                    function(x){
                      paste0(x$published$`date-parts`[1:2], collapse = "/")
                    })

pub_dates <- as.Date(pub_dates, format = "%Y/%M")

keys <- order(pub_dates, decreasing = T)

publications_bibtex <- lapply(seq_along(pubs), 
                              function(x){
                                utils::toBibtex(
                                  utils::bibentry(
                                    bibtype = "Article",
                                    title = pubs[[x]]$title,
                                    author = paste0(paste0(pubs[[x]]$author$given, " ", pubs[[x]]$author$family), collapse = ", "),
                                    journal = paste0( pubs[[x]]$`container-title`, ". Citations: ", pubs[[x]]$`is-referenced-by-count`),
                                    year = pubs[[x]]$issued$`date-parts`[[1]],
                                    url = pubs[[x]]$DOI,
                                    note = paste0("Citations: ", pubs[[x]]$`is-referenced-by-count`),
                                    key=paste0(keys[[x]]))
                                )
                              })

publications_bibtex <- publications_bibtex[keys]

bibfilepath="pubs.bib"

if (file.exists(bibfilepath)){
  file.remove(bibfilepath)
}

con = file(description = bibfilepath, open = "a", blocking = TRUE,
           encoding = "UTF-8", raw = FALSE)

for (i in publications_bibtex){
  writeLines(i,con)
}

close(con)

```

```{r bibliography}
bibliography_entries(bibfilepath)
```

# Teaching

## Invited Guest Lectures

```{r teaching-invited}
# year	university	course
invited_guest_lecture <- data.table::fread(here::here("data/invited_guest_lecture.tsv"), sep = "\t")

detailed_entries(data = invited_guest_lecture[order((invited_guest_lecture$year), decreasing = T),],
                 what = course, 
                 when = year,
                 where = university)
```

