---
name: Chase Clark
address: "University of Wisconsin-Madison, School of Pharmacy"
www: chasemc.github.io
email: "chasingmicrobes@gmail.com"
twitter: ChasingMicrobes
github: chasemc
linkedin: hirechase
date: "`r format(Sys.time(), '%B %Y')`"
output: function(...) {source('resume_entries.R');vitae:::set_entry_formats(resume_entries);vitae::cv_document(..., template = "resume_template.tex", citation_package = "biblatex")}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(vitae)
library(data.table)
library(glue)
library(lubridate)
library(dplyr)
library(jsonlite)
library(httr2)
pipe_assign <- function(x) x
```


```{r orcid-data}
url <- "https://pub.orcid.org/v3.0/0000-0001-6439-9397/educations"
resp <- request(url) %>% req_headers(Accept = "application/vnd.orcid+json")  %>% req_perform() %>% resp_body_json() 
a <- sapply(resp$`affiliation-group`, function(x) x$summaries)
a <- lapply(a, function(x) {list(
    "Degree" = x$`education-summary`$`role-title`,
    "Year" = x$`education-summary`$`start-date`$year$value,
    "Institution"= x$`education-summary`$organization$name,
    "Where" = paste0(
        x$`education-summary`$organization$address$city,
        ", ",
        x$`education-summary`$organization$address$region
    )
)})
orcid_data <- data.table::rbindlist(a, fill=TRUE)
```

# Employment

```{r employment}
detailed_entries(data = orcid_data,
                 what = Degree, 
                 when = Year,
                 with =  Institution,
                 where = Where)
```

# Experience

```{r experience}
job_titles <- data.table::fread(here::here("data", "job-titles.csv"), sep = "\t")

job_descriptions <- data.table::fread(here::here("data", "job-descriptions.csv"), sep = ",")

jobs <- merge(job_titles, 
                          job_descriptions, 
                          by = "jobId", 
                          all.x = T) 

data.table::setorderv(jobs,
                      c("begin","descId"),
                      order=c(-1, 1))


vitae::detailed_entries(jobs,
                        what = position,
                        when = as.character(
                          glue("{lubridate::month(begin, label = TRUE, abbr = TRUE)} {lubridate::year(begin)} - 
           {ifelse(!is.na(end), 
           paste(lubridate::month(end, label = TRUE, abbr = TRUE), lubridate::year(end)), 'present')}")),
           with = employer,
           where = glue("{city}, {region}, {country}"),
           why = accomplishments)
```
\newpage

# Data Science Skills

```{r}
library(dplyr)
skills <- fread("../data/skills.csv")

skills_formatted <- skills %>% 
  mutate(skill = if_else(is.na(details), glue("{skill}"), glue("{skill} ({details})"))) %>% 
  group_by(group) %>% 
  summarize(skills = glue_collapse(skill, sep = " $\\bullet$ "))
```

```{r, results='asis', width = 40000}
for (group in skills_formatted$group) {
  cat(
    glue("\\textbf{<<tools::toTitleCase(group)>>}:", .open = "<<", .close = ">>"),
    filter(skills_formatted, group == !!group)$skills,
    "\n\n\n"
  )
}
```

# Select Individual Software Projects

```{r software-individual}

software <- data.table::fread(here::here("data/software.csv"), sep = "\t")

software <- software[software$group == "solo", ]

detailed_entries(data = software[order(software$year, decreasing = T),],
                 what = name,
                 when = year,
                 with = language,
                 where = description)
```

# Select Team Software Projects

```{r software-team}

software <- data.table::fread(here::here("data/software.csv"), sep = "\t")

software <- software[software$group == "team", ]

detailed_entries(data = software[order(software$year, decreasing = T),], 
                 what = name,
                 when = year,
                 with = language,
                 where = description)

```

# Talks

```{r talks}

oral <- data.table::fread(here::here("data/oral_contributed.csv"), sep = "\t")

detailed_entries(data = oral[order(as.Date(oral$year), decreasing = T),],
                 what = meeting, 
                 when = year,
                 why = title)
```

# Awards

```{r awards}

grants <- data.table::fread(here::here("data/awards.csv"), sep = "\t", fill=T)

grants$end <- ifelse(is.na(grants$end), "present", grants$end)
grants$year <- ifelse(is.na(grants$begin), grants$end, paste0(grants$begin, "-", grants$end))


brief_entries(data =  grants[order(grants$end, decreasing = T),],
              what = award,
              when = year,
              with = amount)

```

# Publications

```{r publications, include=FALSE}

puburls <- data.table::fread(here::here("data","papers.csv"))$doi

crossref_api <- paste0("https://api.crossref.org/v1/works/", puburls)

pubs <- lapply(crossref_api, 
               function(x){
                 jsonlite::fromJSON(x)$message
               })

pub_dates <- sapply(pubs, 
                    function(x){
                      paste0(x$published$`date-parts`[1:2], collapse = "/")
                    })

pub_dates <- as.Date(pub_dates, format = "%Y/%M")

keys <- order(pub_dates, decreasing = T)

publications_bibtex <- lapply(seq_along(pubs), 
                              function(x){
                                utils::toBibtex(
                                  utils::bibentry(
                                    bibtype = "Article",
                                    title = pubs[[x]]$title,
                                    author = paste0(paste0(pubs[[x]]$author$given, " ", pubs[[x]]$author$family), collapse = ", "),
                                    journal = paste0( pubs[[x]]$`container-title`, ". Citations: ", pubs[[x]]$`is-referenced-by-count`),
                                    year = pubs[[x]]$issued$`date-parts`[[1]],
                                    url = pubs[[x]]$DOI,
                                    note = paste0("Citations: ", pubs[[x]]$`is-referenced-by-count`),
                                    key=paste0(keys[[x]]))
                                )
                              })

publications_bibtex <- publications_bibtex[keys]

bibfilepath="pubs.bib"

if (file.exists(bibfilepath)){
  file.remove(bibfilepath)
}

con = file(description = bibfilepath, open = "a", blocking = TRUE,
           encoding = "UTF-8", raw = FALSE)

for (i in publications_bibtex){
  writeLines(i,con)
}

close(con)

```

```{r}


bibliography_entries(bibfilepath)

```


