# Publish GitHub workflow artifacts tutorial example
name: Build pdfs

on:
  push:
    branches: [ main ]

jobs:
  build-push-resume:
    if: "!contains(github.event.head_commit.message, 'docker')"
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/chasemc/resume:main 
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run rmarkdown
        env:
          ORCID_TOKEN: ${{ secrets.ORCID_TOKEN }}
        run: |
          Rscript -e  'rmarkdown::render("resume/resume.Rmd")'
          Rscript -e  'rmarkdown::render("cv/cv.Rmd")'
          mv resume.pdf resume/resume.pdf
          mv cv.pdf cv/cv.pdf
        
      - name: Commit and push changes
        run: |
          git config --global user.name "chasemc"
          git config --global user.email "18691127+chasemc@users.noreply.github.com"

          git add -A
          git commit -m "auto-update"
          git push


